version: '3'
services:
  btjs-search-1:
    image: elasticsearch:8.15.0
    container_name: btjs-search-1
    environment:
      - cluster.name=btjs-search
      - node.name=btjs-search-1
      - "discovery.type=single-node" # disables bootstrap checks that are enabled when network.host is set to a non-loopback address
      - xpack.security.enabled=false
    volumes:
      - btjs-search-1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - btjs-search-docker-net

  btjs-kibana:
    image: kibana:8.15.0
    container_name: btjs-kibana
    volumes:
      - btjs-kibana:/usr/share/kibana
    ports:
      - 5601:5601
    networks:
      - btjs-search-docker-net

  # btjs-dashboards:
  #   image: opensearchproject/opensearch-dashboards:latest
  #   container_name: btjs-dashboards
  #   environment:
  #     - 'OPENSEARCH_HOSTS=["http://btjs-search-1:9200"]'
  #     - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards
  #   ports:
  #     - 5601:5601
  #   expose:
  #     - "5601"
  #   networks:
  #     - btjs-search-docker-net

volumes:
  btjs-search-1:
  btjs-kibana:

networks:
  btjs-search-docker-net:
